version: '3.6'
services:
        engmaster_bot:
                build:
                        context: .
                        dockerfile: Dockerfile.engmaster_bot
                restart: always
                depends_on:
                        postgres:
                                condition: service_started

        postgres:
                build:
                        context: .
                        dockerfile: Dockerfile.postgres
                restart: always
                volumes:
                        - $PWD/data/postgres:/var/lib/postgresql/data
                        - $PWD/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
                environment:
                        - POSTGRES_PASSWORD=cabeiMoh4Pah
                        - POSTGRES_USER=engmaster